#SPDX-License-Identifier: MIT-0
namespace: arubanetworks

name: hpeanw_central

version: 2.0.0-beta

readme: README.md

authors:
- Ti Chiapuzio-Wong tcwong@hpe.com

description: A collection of Ansible modules and plugins for HPE Aruba Networking Central and HPE GreenLake Platform APIs.

license:
- GPL-3.0-or-later

tags: ['aruba', 'hpe', 'central', 'greenlake', 'networking', 'cloud', 'inventory', 'api']

repository: https://github.com/aruba/aruba-central-ansible-collection/tree/v2-beta

documentation: https://github.com/aruba/aruba-central-ansible-collection/tree/v2-beta/docs

issues: https://github.com/aruba/aruba-central-ansible-collection/issues