---
# Example playbook for Configuration Profiles in HPE Aruba Networking Central
- name: Create Library Profiles in HPE Aruba Networking Central
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new Library VLAN profile
      arubanetworks.hpeanw_central.central_profiles:
        base_url: "{{ central_base_url }}"
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
        workspace_id: "{{ glp_workspace_id }}"
        name: 100
        path: "layer2-vlan"
        config_dict:
          vlan: 100
          name: "Corp-VLAN"
          description: "Corporate VLAN for main office"
        state: merged

    - name: Create Library Default Gateway
      arubanetworks.hpeanw_central.central_profiles:
        base_url: "{{ central_base_url }}"
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
        workspace_id: "{{ glp_workspace_id }}"
        name: rsvl-default-gateway
        path: static-route
        state: merged
        config_dict:
          default-gateway:
            - dg-name: rsvl-default-gateway
              forwarding-type: "NEXTHOP"
              ipv4-address: "192.168.0.1"

    - name: Create Library VRFs
      arubanetworks.hpeanw_central.central_profiles:
        base_url: "{{ central_base_url }}"
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
        workspace_id: "{{ glp_workspace_id }}"
        name: "{{item}}"
        path: vrfs
        state: merged
        config_dict:
          name: "{{item}}"
      loop:
        - rsvl-corp
        - rsvl-guest