---
# Example playbook to Create Sites and Assign Devices in HPE Aruba Networking Central
- name: Create Sites and Assign Devices in HPE Aruba Networking Central
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new Site
      arubanetworks.hpeanw_central.central_sites:
        base_url: "{{ central_base_url }}"
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
        workspace_id: "{{ glp_workspace_id }}"
        site_attributes:
          name: Ansible Campus
          address: "123 S St"
          city: "Sacramento"
          state: "California"
          country: "United States"
          zipcode: "12345"
          timezone: "America/Los_Angeles"
        state: merged

    - name: Assign Devices to Sites Using Classic HPE Aruba Networking Central API
      arubanetworks.hpeanw_central.classic_sites:
        base_url: "{{ classic_base_url }}"
        access_token: "{{ classic_access_token }}"
        site_name: "Ansible Campus"
        device_type: "ACCESS_POINT"
        devices:
          - "AABBCCDD11"
          - "DDCCBBAA22"
        state: assigned
      register: sites_result
