---
- name: Demp HPE GreenLake Platform API Calls
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate Token for Session
      arubanetworks.hpeanw_central.glp_token:
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
      register: token_result
      no_log: True

    # Get device inventory from GLP
    - name: Retrieve Devices from GLP
      arubanetworks.hpeanw_central.glp_devices_info:
        access_token: "{{token_result['access_token']}}"
      register: glp_device_inventory

    - debug:
        var: glp_device_inventory