---
- name: Demp HPE GreenLake Platform API Calls
  hosts: localhost
  gather_facts: no
  tasks:
    # Get device inventory from GLP
    - name: Retrieve Devices from GLP
      arubanetworks.hpeanw_central.glp_devices_info:
        client_id: "{{ glp_client_id }}"
        client_secret: "{{ glp_client_secret }}"
        workspace_id: "{{ glp_workspace_id }}"
      register: glp_device_inventory

    - debug:
        var: glp_device_inventory